-- Esquema Oracle de l'historic corporatiu de la sala de fatiga.
--
-- Es desplega dins l'esquema propi acordat amb IT (p. ex. SALAFATIGA).
-- L'usuari de servei amb que es connecta el PC LAB ha de tenir privilegis
-- de CREATE TABLE / CREATE INDEX al seu propi esquema, o bé un DBA ha
-- d'executar aquest script una sola vegada per crear-ho.
--
-- Tipus equivalents respecte de l'esquema SQLite:
--   REAL    -> BINARY_DOUBLE  (ts UNIX, valors d'enginyeria)
--   INTEGER -> NUMBER(10,0)   (raw, status_code, severity, addr)
--   TEXT    -> VARCHAR2       (identificadors curts) o CLOB si calgues
--
-- Convencions:
--   - Tots els camps estan en majúscules per ser idiomatics a Oracle.
--   - Es manté la mateixa semàntica que l'esquema SQLite (mateixos noms
--     de columna, mateixos valors enumerats com a strings).
--
-- Aquest script es pot executar diverses vegades sense errors fatals
-- (els CREATE protegits amb PL/SQL ignoren l'error d'objecte existent).

-- --------------------------------------------------------------------- --
--  Meta
-- --------------------------------------------------------------------- --
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE SCHEMA_META (
            KEY    VARCHAR2(64)  PRIMARY KEY,
            VALUE  VARCHAR2(256) NOT NULL
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

MERGE INTO SCHEMA_META m
USING (SELECT 'schema_version' AS K, '1' AS V FROM DUAL) s
ON (m.KEY = s.K)
WHEN MATCHED THEN UPDATE SET m.VALUE = s.V
WHEN NOT MATCHED THEN INSERT (KEY, VALUE) VALUES (s.K, s.V);

-- --------------------------------------------------------------------- --
--  Catalegs
-- --------------------------------------------------------------------- --
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE DEVICES (
            ID          VARCHAR2(64) PRIMARY KEY,
            DESCRIPCIO  VARCHAR2(512) DEFAULT '''' NOT NULL,
            ADDR        NUMBER(3,0),
            ACTIVE      NUMBER(1,0)   DEFAULT 1 NOT NULL,
            CREATED_AT  BINARY_DOUBLE DEFAULT 0 NOT NULL
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE VARIABLES (
            ID          VARCHAR2(64)  PRIMARY KEY,
            NOM         VARCHAR2(128) NOT NULL,
            ORIGIN      VARCHAR2(16)  NOT NULL,
            KIND        VARCHAR2(16)  NOT NULL,
            UNIT        VARCHAR2(32)  DEFAULT '''' NOT NULL,
            PER_EQUIP   NUMBER(1,0)   DEFAULT 1 NOT NULL,
            DESCRIPCIO  VARCHAR2(512) DEFAULT '''' NOT NULL
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- --------------------------------------------------------------------- --
--  Series temporals de mesures
-- --------------------------------------------------------------------- --
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE MEASUREMENTS (
            ID           NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TS           BINARY_DOUBLE  NOT NULL,
            EQUIP_ID     VARCHAR2(64)   NOT NULL,
            ORIGIN       VARCHAR2(16)   NOT NULL,
            VARIABLE_ID  VARCHAR2(64)   NOT NULL,
            VALUE        BINARY_DOUBLE,
            UNIT         VARCHAR2(32)   DEFAULT '''' NOT NULL,
            QUALITY      VARCHAR2(16)   NOT NULL,
            RAW          NUMBER(10,0),
            STATUS_CODE  NUMBER(10,0),
            NOTE         VARCHAR2(1024) DEFAULT '''' NOT NULL
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MEAS_TS         ON MEASUREMENTS (TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MEAS_EQ_VAR_TS  ON MEASUREMENTS (EQUIP_ID, VARIABLE_ID, TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MEAS_VAR_TS     ON MEASUREMENTS (VARIABLE_ID, TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- --------------------------------------------------------------------- --
--  Esdeveniments / alarmes / estats
-- --------------------------------------------------------------------- --
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE EVENTS (
            ID           NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TS           BINARY_DOUBLE  NOT NULL,
            EQUIP_ID     VARCHAR2(64)   NOT NULL,
            ORIGIN       VARCHAR2(16)   NOT NULL,
            TYPE         VARCHAR2(32)   NOT NULL,
            SEVERITY     NUMBER(3,0)    NOT NULL,
            CODE         VARCHAR2(64)   NOT NULL,
            MESSAGE      VARCHAR2(1024) NOT NULL,
            VARIABLE_ID  VARCHAR2(64),
            VALUE        BINARY_DOUBLE
        )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_EVT_TS       ON EVENTS (TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_EVT_EQ_TS    ON EVENTS (EQUIP_ID, TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_EVT_CODE_TS  ON EVENTS (CODE, TS)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
